# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bd906c83643b7ffc1ffd5e98c286630066db4089f88ac98fe85f5f8f62b19a4dddd3a56fb103b4a92a97fcbcaefda7398ab6bbf17d3150031e73da345fdf852

test:
  secret_key_base: 21cc9ff1512998b2f3564d5fcb480e3dc06d0251f4ae5ea9b9257b8ee22f328c4ac6d9cd96be911dc8c99aa5baa9b8cc900864bfb3df9781466ff8cb764a567d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
